WebApp/Models/Employes/EmployeViewModel.cs
using BiblioClass.Entity;
using BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApp.Models.Employes
{
    public class EmployeViewModel
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }

        public static EmployeViewModel PopulateById(int employeId)
        {
            Employe employe = Manager.Instance.getEmploye(employeId);
            EmployeViewModel employeVm = new EmployeViewModel
            {
                Id = employe.Id,
                Nom = employe.Nom,
                Prenom = employe.Prenom
            };

            return employeVm;
        }
    }
}

WebApp/Models/Offres/OffreViewModel.cs
using BiblioClass.Entity;
using BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApp.Models.Offres
{
    public class OffreViewModel
    {
        public int Id { get; set; }
        public string Intitule { get; set; }
        public string Description { get; set; }
        public DateTime Date { get; set; }
        public double Salaire { get; set; }
        public string Responsable { get; set; }
        public bool HasPostuled { get; set; }

        public static List<OffreViewModel> PopulatesByContain(string searchBar)
        {
            List<Offre> offres = Manager.Instance.GetOffresByContain((searchBar != null) ? searchBar : "");
            List<OffreViewModel> offresVm = new List<OffreViewModel>();
            foreach (var offre in offres)
            {
                offresVm.Add(new OffreViewModel { Id = offre.Id, Intitule = offre.Intitule, Date = offre.Date });
            }

            return offresVm;
        }

        public static OffreViewModel PopulateById(int offreId)
        {
            bool hasPostuled = Manager.Instance.GetPostulationByOffreId(offreId) != null;

            Offre offre = Manager.Instance.getOffre(offreId);
            OffreViewModel offreVm = new OffreViewModel
            {
                Id = offre.Id,
                Intitule = offre.Intitule,
                Description = offre.Description,
                Date = offre.Date,
                Salaire = offre.Salaire,
                Responsable = offre.Responsable,
                HasPostuled = hasPostuled
            };

            return offreVm;
        }
    }
}

WebApp/Models/Postulation/PostulationViewModel.cs
using BiblioClass.Entity;
using BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebApp.Models.Employes;
using WebApp.Models.Offres;

namespace WebApp.Models.Postulations
{
    public class PostulationViewModel
    {
        public string Date { get; set; }
        public string Statut { get; set; }
        public OffreViewModel Offre { get; set; }
        public EmployeViewModel Employe { get; set; }

        public static List<PostulationViewModel> PopulatesById(int employeId)
        {
            List<Postulation> postulations = Manager.Instance.GetPostulationByEmployeId(employeId);
            List<PostulationViewModel> postulationsVm = new List<PostulationViewModel>();
            foreach (var postulation in postulations)
            {
                postulationsVm.Add(new PostulationViewModel
                {
                    Date = postulation.Date,
                    Statut = postulation.Statut,
                    Offre = OffreViewModel.PopulateById(postulation.OffreId),
                    Employe = EmployeViewModel.PopulateById(postulation.EmployeId)
                });
            }

            return postulationsVm;
        }
    }
}

WebApp/Controllers/DetailController.cs
using BiblioClass.Entity;
using BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Models.Offres;

namespace WebApp.Controllers
{
    public class DetailController : Controller
    {
        private Manager manager;

        public DetailController()
        {
            manager = Manager.Instance;
        }

        public ActionResult Index(int id)
        {
            return View(OffreViewModel.PopulateById(id));
        }

        public ActionResult RegisterPostulation(int id)
        {
            if (OffreViewModel.PopulateById(id).HasPostuled)
            {
                manager.RemovePostulation(id);
            }
            else
            {
                manager.InsertPostulation(id);
            }
            return View(OffreViewModel.PopulateById(id));
        }
    }
}

WebApp/Controllers/OffresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BiblioClass.Entity;
using BLL;
using WebApp.Models.Offres;

namespace WebApp.Controllers
{
    public class OffresController : Controller
    {
        public ActionResult Index(string searchBar)
        {
            return View(OffreViewModel.PopulatesByContain(searchBar));
        }
    }
}

WebApp/Controllers/PostulationController.cs
using BiblioClass.Entity;
using BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Models.Postulations;

namespace WebApp.Controllers
{
    public class PostulationController : Controller
    {
        public ActionResult Index()
        {
            return View(PostulationViewModel.PopulatesById(5));
        }
    }
}

WebApp/Views/Detail/Index.cshtml
@using WebApp.Models.Offres
@model OffreViewModel
@{
    ViewBag.Title = "Index";
}

<h2>Détail de l'offre</h2>
<div class="container bg-primary" style="padding-bottom: 2rem;">
    <h3>@Model.Intitule</h3>
    <h4>Responsable : @Model.Responsable</h4>
    <p class="bg-info" style="color: #333; padding: 2rem;">@Model.Description</p>

    <div>
        Réf: #@Model.Id<br />
        Date de publication : @Model.Date<br />
        Salaire : @Model.Salaire £
    </div>

    <hr />

    @if (Model.HasPostuled)
    {
        <a href="@Url.Action("RegisterPostulation", "Detail", new { id = Model.Id })" class="btn btn-danger">Enlever la postulation</a>
    }
    else
    {
        <a href="@Url.Action("RegisterPostulation", "Detail", new { id = Model.Id })" class="btn btn-success">Je postule</a>
    }
</div>

WebApp/Views/Detail/RegisterPostulation.cshtml
@using WebApp.Models.Offres
@model OffreViewModel
@{
    ViewBag.Title = "Information";
}

<h2>@ViewBag.Title</h2>
<div class="container bg-success" style="padding-bottom: 2rem;">
    <h3>Modification effectué</h3>
    <p>Offre modifié : @Model.Intitule</p>

    <hr />

    <a href="@Url.Action("Index", "Detail" , new { id=Model.Id })" class="btn btn-success">Retour</a>
</div>

WebApp/Views/Offres/Index.cshtml
@using WebApp.Models.Offres
@model List<OffreViewModel>
@{
    ViewBag.Title = "Liste des offres";
}
<h2>@ViewBag.Title</h2>

<div>
    <form style="margin: 3rem">
        <label>Rechercher une offre</label>
        <div>
            @Html.TextBox("searchBar", "", new { placeholder = "Rechercher..." })
            <input type="submit" />
        </div>
    </form>

    <div class="container-fluid bg-primary">
        @Html.Partial("ListeOffre")
    </div>
</div>

WebApp/Views/Offres/ListeOffre.cshtml
<h3>Liste des offres</h3>
<div>
@foreach (var offre in Model)
{
    <a href="@Url.Action("Index", "Detail", new { id = @offre.Id })" class="container-fluid bg-info" style="display: block; color: #333; margin: 1rem; cursor: pointer;">
        <h4>@offre.Intitule</h4>
        <div>@offre.Date</div>
    </a>
}
</div>

WebApp/Views/Postulation/Index.cshtml
@using WebApp.Models.Postulations
@model List<PostulationViewModel>
@{
    ViewBag.Title = "Liste des postulations";
}

<h2>@ViewBag.Title</h2>
<div class="container-fluid bg-primary">
@foreach (var postulation in Model)
{
    <div class="container-fluid bg-info" style="display: block; color: #333; margin: 1rem;">
        <div>Date : @postulation.Date</div>
        <div>Statut : @postulation.Statut</div>
        <div>Offre : @postulation.Offre.Intitule</div>
        <div>Employé : @postulation.Employe.Prenom @postulation.Employe.Nom</div>
    </div>
}
</div>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Liste des offres", "Index", "Offres", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div>
                @Html.ActionLink("Liste des postulations", "Index", "Postulation", new { area = "" }, new { @class = "navbar-text" });
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mon application ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>